print('___________')
print('|          |')
print('|          |')
print('|__________|')
print('     |      ')
print('     |      ')
print('     |      ')
print('   ------   ')
print('  /  |    \  ')
print(' /   |     \ ')
print('/    |      \ ')
print('     |       ')
print('     |       ')
print('     |       ')
print('   ------    ')
print('  /      \   ')
print(' /        \  ')
print('/          \ ')
print('|          | ')
print('|          | ')